from enum import Enum


class SessionMode(Enum):
    """
   Enumeration of supported conversation modes for the assistant.

   Attributes:
       RANDOM (str): Sends random technical trivia facts.
       GPT (str): Chat mode for general-purpose GPT assistant.
       TALK (str): Chat mode to talk with a famous person.
       CHOOSE_PERSONALITY (str): Chooses a famous person.
       QUIZ (str): Chat mode for quiz-based interaction.
       TRANSLATE (str): Chat mode for translate text.
       RESUME (str): Chat mode for create resume.
       VOICE_CHAT (str): Chat mode for voice chat with chatGPT.
    """
    RANDOM = "random"
    GPT = "gpt"
    TALK, CHOOSE_PERSONALITY = "talk", "choose"
    QUIZ = "quiz"
    TRANSLATE = "translate"
    RESUME = "resume"
    VOICE_CHAT = "VOICE_CHAT"


class MessageRole(Enum):
    """
    Enumeration of message roles used in conversation history.

    Attributes:
        USER (str): Message sent by the Telegram user.
        ASSISTANT (str): Message generated by the OpenAI assistant.
        SYSTEM (str): Optional system instructions (e.g., prompts).
    """
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"